Importing modules:

In [1]:
import pandas as pd
import numpy as np
from pandas_datareader import data

Load data:

In [14]:
# We would like all available data from 01/01/2000 until 12/31/2016.
start_date = '2010-01-01'
end_date = '2020-12-31'

# User pandas_reader.data.DataReader to load the desired data. As simple as that.
fb_df = data.DataReader('FB', 'yahoo', start_date, end_date)

In [15]:
fb_df.head()

                 High        Low       Open      Close     Volume  Adj Close
Date
2012-05-18  45.000000  38.000000  42.049999  38.230000  573576400  38.230000
2012-05-21  36.660000  33.000000  36.529999  34.029999  168192700  34.029999
2012-05-22  33.590000  30.940001  32.610001  31.000000  101786600  31.000000
2012-05-23  32.500000  31.360001  31.370001  32.000000   73600000  32.000000
2012-05-24  33.209999  31.770000  32.950001  33.029999   50237200  33.029999

# Save:

Save facebook stock to csv:

In [16]:
fb_df.to_csv(r'FB_Stocks.csv')

Data from May 2020:

In [17]:
fb_may_last_year = fb_df[(fb_df.index.year == 2020) & (fb_df.index.month == 5) ]
fb_may_last_year

                  High         Low  ...    Volume   Adj Close
Date                                ...
2020-05-01  207.279999  199.050003  ...  30415600  202.270004
2020-05-04  205.910004  198.759995  ...  19250700  205.259995
2020-05-05  210.380005  206.500000  ...  21071200  207.070007
2020-05-06  211.600006  206.660004  ...  21857000  208.470001
2020-05-07  211.600006  209.039993  ...  15152000  211.259995
2020-05-08  213.210007  210.850006  ...  12524000  212.350006
2020-05-11  215.000000  210.369995  ...  12911900  213.179993
2020-05-12  215.279999  210.000000  ...  14704600  210.100006
2020-05-13  210.779999  202.110001  ...  20684600  205.100006
2020-05-14  206.929993  200.690002  ...  17178900  206.809998
2020-05-15  211.339996  204.119995  ...  19375200  210.880005
2020-05-18  214.639999  210.940002  ...  20167400  213.190002
2020-05-19  220.490005  212.830002  ...  31843200  216.880005
2020-05-20  231.339996  223.190002  ...  50162900  229.970001
2020-05-21  237.199997  231.199997  ...  47782600  231.389999
2020-05-22  235.990005  228.740005  ...  33925600  234.910004
2020-05-26  240.899994  231.669998  ...  33178300  232.199997
2020-05-27  230.559998  221.130005  ...  34697600  229.139999
2020-05-28  231.630005  224.000000  ...  29377200  225.460007
2020-05-29  227.490005  222.880005  ...  23322500  225.089996

[20 rows x 6 columns]

Save data from last May to csv:

In [18]:
fb_may_last_year.to_csv('fb_May_2020.csv')

Save data to Excel file:

In [22]:
fb_may_last_year.to_excel('fb_may_excel.xlsx',sheet_name= 'May')

# Read data:

Read data from CSV:

In [20]:
fb_may_20 = pd.read_csv('fb_May_2020.csv',index_col=0)
fb_may_20.head()

                  High         Low  ...    Volume   Adj Close
Date                                ...
2020-05-01  207.279999  199.050003  ...  30415600  202.270004
2020-05-04  205.910004  198.759995  ...  19250700  205.259995
2020-05-05  210.380005  206.500000  ...  21071200  207.070007
2020-05-06  211.600006  206.660004  ...  21857000  208.470001
2020-05-07  211.600006  209.039993  ...  15152000  211.259995

[5 rows x 6 columns]

Read data from Excel:

In [24]:
from_excel = pd.read_excel('fb_may_excel.xlsx',index_col= 0,sheet_name='May')
from_excel

                  High         Low  ...    Volume   Adj Close
Date                                ...
2020-05-01  207.279999  199.050003  ...  30415600  202.270004
2020-05-04  205.910004  198.759995  ...  19250700  205.259995
2020-05-05  210.380005  206.500000  ...  21071200  207.070007
2020-05-06  211.600006  206.660004  ...  21857000  208.470001
2020-05-07  211.600006  209.039993  ...  15152000  211.259995
2020-05-08  213.210007  210.850006  ...  12524000  212.350006
2020-05-11  215.000000  210.369995  ...  12911900  213.179993
2020-05-12  215.279999  210.000000  ...  14704600  210.100006
2020-05-13  210.779999  202.110001  ...  20684600  205.100006
2020-05-14  206.929993  200.690002  ...  17178900  206.809998
2020-05-15  211.339996  204.119995  ...  19375200  210.880005
2020-05-18  214.639999  210.940002  ...  20167400  213.190002
2020-05-19  220.490005  212.830002  ...  31843200  216.880005
2020-05-20  231.339996  223.190002  ...  50162900  229.970001
2020-05-21  237.199997  231.199997  ...  47782600  231.389999
2020-05-22  235.990005  228.740005  ...  33925600  234.910004
2020-05-26  240.899994  231.669998  ...  33178300  232.199997
2020-05-27  230.559998  221.130005  ...  34697600  229.139999
2020-05-28  231.630005  224.000000  ...  29377200  225.460007
2020-05-29  227.490005  222.880005  ...  23322500  225.089996

[20 rows x 6 columns]

# London bike share:

In this case use dataset from:
https://www.kaggle.com/hmavrodiev/london-bike-sharing-dataset

Load data:

In [28]:
raw_df = pd.read_csv('london_merged.csv')
raw_df

                 timestamp   cnt   t1  ...  is_holiday  is_weekend  season
0      2015-01-04 00:00:00   182  3.0  ...         0.0         1.0     3.0
1      2015-01-04 01:00:00   138  3.0  ...         0.0         1.0     3.0
2      2015-01-04 02:00:00   134  2.5  ...         0.0         1.0     3.0
3      2015-01-04 03:00:00    72  2.0  ...         0.0         1.0     3.0
4      2015-01-04 04:00:00    47  2.0  ...         0.0         1.0     3.0
...                    ...   ...  ...  ...         ...         ...     ...
17409  2017-01-03 19:00:00  1042  5.0  ...         0.0         0.0     3.0
17410  2017-01-03 20:00:00   541  5.0  ...         0.0         0.0     3.0
17411  2017-01-03 21:00:00   337  5.5  ...         0.0         0.0     3.0
17412  2017-01-03 22:00:00   224  5.5  ...         0.0         0.0     3.0
17413  2017-01-03 23:00:00   139  5.0  ...         0.0         0.0     3.0

[17414 rows x 10 columns]

Information about columns:

In [29]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17414 entries, 0 to 17413
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   timestamp     17414 non-null  object
 1   cnt           17414 non-null  int64
 2   t1            17414 non-null  float64
 3   t2            17414 non-null  float64
 4   hum           17414 non-null  float64
 5   wind_speed    17414 non-null  float64
 6   weather_code  17414 non-null  float64
 7   is_holiday    17414 non-null  float64
 8   is_weekend    17414 non-null  float64
 9   season        17414 non-null  float64
dtypes: float64(8), int64(1), object(1)
memory usage: 1.3+ MB

In [34]:
raw_df.index =  raw_df.timestamp
raw_df= raw_df.drop(columns=['timestamp'])
raw_df

                      cnt   t1   t2  ...  is_holiday  is_weekend  season
timestamp                            ...
2015-01-04 00:00:00   182  3.0  2.0  ...         0.0         1.0     3.0
2015-01-04 01:00:00   138  3.0  2.5  ...         0.0         1.0     3.0
2015-01-04 02:00:00   134  2.5  2.5  ...         0.0         1.0     3.0
2015-01-04 03:00:00    72  2.0  2.0  ...         0.0         1.0     3.0
2015-01-04 04:00:00    47  2.0  0.0  ...         0.0         1.0     3.0
...                   ...  ...  ...  ...         ...         ...     ...
2017-01-03 19:00:00  1042  5.0  1.0  ...         0.0         0.0     3.0
2017-01-03 20:00:00   541  5.0  1.0  ...         0.0         0.0     3.0
2017-01-03 21:00:00   337  5.5  1.5  ...         0.0         0.0     3.0
2017-01-03 22:00:00   224  5.5  1.5  ...         0.0         0.0     3.0
2017-01-03 23:00:00   139  5.0  1.0  ...         0.0         0.0     3.0

[17414 rows x 9 columns]